version: '3.8'

services:

  mongo:
    container_name: MongoDatabase
    image: mongo:7.0.0
    restart: always
    ports:
      - 27028:27017
    volumes:
      - mongdb_data_container:/data/db

  mongo-express:
    container_name: MongoDatabase-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  tracing:
    container_name: Tracing
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  redis:
    container_name: Redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  mongdb_data_container:
