export const countries: any = {
  name: 'countries',
  items: [
    { id: '1', label: 'Afghanistan', order: 1 },
    { id: '2', label: 'Albania', order: 2 },
    { id: '3', label: 'Algeria', order: 3 },
    { id: '4', label: 'Andorra', order: 4 },
    { id: '5', label: 'Angola', order: 5 },
    { id: '6', label: 'Antigua and Barbuda', order: 6 },
    { id: '7', label: 'Argentina', order: 7 },
    { id: '8', label: 'Armenia', order: 8 },
    { id: '9', label: 'Australia', order: 9 },
    { id: '10', label: 'Austria', order: 10 },
    { id: '11', label: 'Azerbaijan', order: 11 },
    { id: '12', label: 'Bahamas', order: 12 },
    { id: '13', label: 'Bahrain', order: 13 },
    { id: '14', label: 'Bangladesh', order: 14 },
    { id: '15', label: 'Barbados', order: 15 },
    { id: '16', label: 'Belarus', order: 16 },
    { id: '17', label: 'Belgium', order: 17 },
    { id: '18', label: 'Belize', order: 18 },
    { id: '19', label: 'Benin', order: 19 },
    { id: '20', label: 'Bhutan', order: 20 },
    { id: '21', label: 'Bolivia', order: 21 },
    { id: '22', label: 'Bosnia and Herzegovina', order: 22 },
    { id: '23', label: 'Botswana', order: 23 },
    { id: '24', label: 'Brazil', order: 24 },
    { id: '25', label: 'Brunei', order: 25 },
    { id: '26', label: 'Bulgaria', order: 26 },
    { id: '27', label: 'Burkina Faso', order: 27 },
    { id: '28', label: 'Burundi', order: 28 },
    { id: '29', label: 'Cabo Verde', order: 29 },
    { id: '30', label: 'Cambodia', order: 30 },
    { id: '31', label: 'Cameroon', order: 31 },
    { id: '32', label: 'Canada', order: 32 },
    { id: '33', label: 'Central African Republic', order: 33 },
    { id: '34', label: 'Chad', order: 34 },
    { id: '35', label: 'Chile', order: 35 },
    { id: '36', label: 'China', order: 36 },
    { id: '37', label: 'Colombia', order: 37 },
    { id: '38', label: 'Comoros', order: 38 },
    { id: '39', label: 'Congo, Democratic Republic of the', order: 39 },
    { id: '40', label: 'Congo, Republic of the', order: 40 },
    { id: '41', label: 'Costa Rica', order: 41 },
    { id: '42', label: 'Croatia', order: 42 },
    { id: '43', label: 'Cuba', order: 43 },
    { id: '44', label: 'Cyprus', order: 44 },
    { id: '45', label: 'Czech Republic', order: 45 },
    { id: '46', label: 'Denmark', order: 46 },
    { id: '47', label: 'Djibouti', order: 47 },
    { id: '48', label: 'Dominica', order: 48 },
    { id: '49', label: 'Dominican Republic', order: 49 },
    { id: '50', label: 'Ecuador', order: 50 },
    { id: '51', label: 'Egypt', order: 51 },
    { id: '52', label: 'El Salvador', order: 52 },
    { id: '53', label: 'Equatorial Guinea', order: 53 },
    { id: '54', label: 'Eritrea', order: 54 },
    { id: '55', label: 'Estonia', order: 55 },
    { id: '56', label: 'Eswatini', order: 56 },
    { id: '57', label: 'Ethiopia', order: 57 },
    { id: '58', label: 'Fiji', order: 58 },
    { id: '59', label: 'Finland', order: 59 },
    { id: '60', label: 'France', order: 60 },
    { id: '61', label: 'Gabon', order: 61 },
    { id: '62', label: 'Gambia', order: 62 },
    { id: '63', label: 'Georgia', order: 63 },
    { id: '64', label: 'Germany', order: 64 },
    { id: '65', label: 'Ghana', order: 65 },
    { id: '66', label: 'Greece', order: 66 },
    { id: '67', label: 'Grenada', order: 67 },
    { id: '68', label: 'Guatemala', order: 68 },
    { id: '69', label: 'Guinea', order: 69 },
    { id: '70', label: 'Guinea-Bissau', order: 70 },
    { id: '71', label: 'Guyana', order: 71 },
    { id: '72', label: 'Haiti', order: 72 },
    { id: '73', label: 'Honduras', order: 73 },
    { id: '74', label: 'Hungary', order: 74 },
    { id: '75', label: 'Iceland', order: 75 },
    { id: '76', label: 'India', order: 76 },
    { id: '77', label: 'Indonesia', order: 77 },
    { id: '78', label: 'Iran', order: 78 },
    { id: '79', label: 'Iraq', order: 79 },
    { id: '80', label: 'Ireland', order: 80 },
    { id: '81', label: 'Israel', order: 81 },
    { id: '82', label: 'Italy', order: 82 },
    { id: '83', label: 'Jamaica', order: 83 },
    { id: '84', label: 'Japan', order: 84 },
    { id: '85', label: 'Jordan', order: 85 },
    { id: '86', label: 'Kazakhstan', order: 86 },
    { id: '87', label: 'Kenya', order: 87 },
    { id: '88', label: 'Kiribati', order: 88 },
    { id: '89', label: 'Korea, North', order: 89 },
    { id: '90', label: 'Korea, South', order: 90 },
    { id: '91', label: 'Kuwait', order: 91 },
    { id: '92', label: 'Kyrgyzstan', order: 92 },
    { id: '93', label: 'Laos', order: 93 },
    { id: '94', label: 'Latvia', order: 94 },
    { id: '95', label: 'Lebanon', order: 95 },
    { id: '96', label: 'Lesotho', order: 96 },
    { id: '97', label: 'Liberia', order: 97 },
    { id: '98', label: 'Libya', order: 98 },
    { id: '99', label: 'Liechtenstein', order: 99 },
    { id: '100', label: 'Lithuania', order: 100 },
    { id: '101', label: 'Luxembourg', order: 101 },
    { id: '102', label: 'Madagascar', order: 102 },
    { id: '103', label: 'Malawi', order: 103 },
    { id: '104', label: 'Malaysia', order: 104 },
    { id: '105', label: 'Maldives', order: 105 },
    { id: '106', label: 'Mali', order: 106 },
    { id: '107', label: 'Malta', order: 107 },
    { id: '108', label: 'Marshall Islands', order: 108 },
    { id: '109', label: 'Mauritania', order: 109 },
    { id: '110', label: 'Mauritius', order: 110 },
    { id: '111', label: 'Mexico', order: 111 },
    { id: '112', label: 'Micronesia', order: 112 },
    { id: '113', label: 'Moldova', order: 113 },
    { id: '114', label: 'Monaco', order: 114 },
    { id: '115', label: 'Mongolia', order: 115 },
    { id: '116', label: 'Montenegro', order: 116 },
    { id: '117', label: 'Morocco', order: 117 },
    { id: '118', label: 'Mozambique', order: 118 },
    { id: '119', label: 'Myanmar', order: 119 },
    { id: '120', label: 'Namibia', order: 120 },
    { id: '121', label: 'Nauru', order: 121 },
    { id: '122', label: 'Nepal', order: 122 },
    { id: '123', label: 'Netherlands', order: 123 },
    { id: '124', label: 'New Zealand', order: 124 },
    { id: '125', label: 'Nicaragua', order: 125 },
    { id: '126', label: 'Niger', order: 126 },
    { id: '127', label: 'Nigeria', order: 127 },
    { id: '128', label: 'North Macedonia', order: 128 },
    { id: '129', label: 'Norway', order: 129 },
    { id: '130', label: 'Oman', order: 130 },
    { id: '131', label: 'Pakistan', order: 131 },
    { id: '132', label: 'Palau', order: 132 },
    { id: '133', label: 'Palestine', order: 133 },
    { id: '134', label: 'Panama', order: 134 },
    { id: '135', label: 'Papua New Guinea', order: 135 },
    { id: '136', label: 'Paraguay', order: 136 },
    { id: '137', label: 'Peru', order: 137 },
    { id: '138', label: 'Philippines', order: 138 },
    { id: '139', label: 'Poland', order: 139 },
    { id: '140', label: 'Portugal', order: 140 },
    { id: '141', label: 'Qatar', order: 141 },
    { id: '142', label: 'Romania', order: 142 },
    { id: '143', label: 'Russia', order: 143 },
    { id: '144', label: 'Rwanda', order: 144 },
    { id: '145', label: 'Saint Kitts and Nevis', order: 145 },
    { id: '146', label: 'Saint Lucia', order: 146 },
    { id: '147', label: 'Saint Vincent and the Grenadines', order: 147 },
    { id: '148', label: 'Samoa', order: 148 },
    { id: '149', label: 'San Marino', order: 149 },
    { id: '150', label: 'Sao Tome and Principe', order: 150 },
    { id: '151', label: 'Saudi Arabia', order: 151 },
    { id: '152', label: 'Senegal', order: 152 },
    { id: '153', label: 'Serbia', order: 153 },
    { id: '154', label: 'Seychelles', order: 154 },
    { id: '155', label: 'Sierra Leone', order: 155 },
    { id: '156', label: 'Singapore', order: 156 },
    { id: '157', label: 'Slovakia', order: 157 },
    { id: '158', label: 'Slovenia', order: 158 },
    { id: '159', label: 'Solomon Islands', order: 159 },
    { id: '160', label: 'Somalia', order: 160 },
    { id: '161', label: 'South Africa', order: 161 },
    { id: '162', label: 'South Sudan', order: 162 },
    { id: '163', label: 'Spain', order: 163 },
    { id: '164', label: 'Sri Lanka', order: 164 },
    { id: '165', label: 'Sudan', order: 165 },
    { id: '166', label: 'Suriname', order: 166 },
    { id: '167', label: 'Sweden', order: 167 },
    { id: '168', label: 'Switzerland', order: 168 },
    { id: '169', label: 'Syria', order: 169 },
    { id: '170', label: 'Taiwan', order: 170 },
    { id: '171', label: 'Tajikistan', order: 171 },
    { id: '172', label: 'Tanzania', order: 172 },
    { id: '173', label: 'Thailand', order: 173 },
    { id: '174', label: 'Timor-Leste', order: 174 },
    { id: '175', label: 'Togo', order: 175 },
    { id: '176', label: 'Tonga', order: 176 },
    { id: '177', label: 'Trinidad and Tobago', order: 177 },
    { id: '178', label: 'Tunisia', order: 178 },
    { id: '179', label: 'Turkey', order: 179 },
    { id: '180', label: 'Turkmenistan', order: 180 },
    { id: '181', label: 'Tuvalu', order: 181 },
    { id: '182', label: 'Uganda', order: 182 },
    { id: '183', label: 'Ukraine', order: 183 },
    { id: '184', label: 'United Arab Emirates', order: 184 },
    { id: '185', label: 'United Kingdom', order: 185 },
    { id: '186', label: 'United States', order: 186 },
    { id: '187', label: 'Uruguay', order: 187 },
    { id: '188', label: 'Uzbekistan', order: 188 },
    { id: '189', label: 'Vanuatu', order: 189 },
    { id: '190', label: 'Vatican City', order: 190 },
    { id: '191', label: 'Venezuela', order: 191 },
    { id: '192', label: 'Vietnam', order: 192 },
    { id: '193', label: 'Yemen', order: 193 },
    { id: '194', label: 'Zambia', order: 194 },
    { id: '195', label: 'Zimbabwe', order: 195 },
  ],
};
